// Generated by CoffeeScript 1.6.2
(function() {
  jQuery(function() {
    return $(".btn-menu").click(function() {
      $(".is-hidden").toggleClass("is-expanded");
      return false;
    });
  });

}).call(this);
